<<<<<<< HEAD
=======
# .github/workflows/ci.yml
>>>>>>> a88b2e37237bb9df611dc3a5345758ec39a6765a
name: Frontend CI

on:
  push:
    branches-ignore:
      - develop
  pull_request:
    branches-ignore:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
<<<<<<< HEAD

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
=======
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
>>>>>>> a88b2e37237bb9df611dc3a5345758ec39a6765a
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
<<<<<<< HEAD
        run: npm run build
=======
        run: npx vite build
>>>>>>> a88b2e37237bb9df611dc3a5345758ec39a6765a
